//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicActivityPhase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcademicActivityPhase()
        {
            this.Forms = new HashSet<Form>();
            this.ParticipantRoles = new HashSet<ParticipantRole>();
            this.AcademicActivityPhaseLanguages = new HashSet<AcademicActivityPhaseLanguage>();
        }
    
        public int phase_id { get; set; }
        public System.DateTime phase_start { get; set; }
        public System.DateTime phase_end { get; set; }
        public int activity_id { get; set; }
        public int created_by { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AcademicActivity AcademicActivity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Form> Forms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParticipantRole> ParticipantRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicActivityPhaseLanguage> AcademicActivityPhaseLanguages { get; set; }
    }
}
