//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicProgram
    {
        public int program_id { get; set; }
        public string program_name { get; set; }
        public System.DateTime program_start_date { get; set; }
        public System.DateTime program_end_date { get; set; }
        public Nullable<int> article_id { get; set; }
        public string note { get; set; }
    
        public virtual News News { get; set; }
    }
}
