//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicCollaborationStatusType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcademicCollaborationStatusType()
        {
            this.CollaborationStatusHistories = new HashSet<CollaborationStatusHistory>();
        }
    
        public int collab_status_type_id { get; set; }
        public Nullable<int> collab_type_id { get; set; }
        public Nullable<int> collab_status_id { get; set; }
    
        public virtual AcademicCollaborationType AcademicCollaborationType { get; set; }
        public virtual AcademicCollaborationStatu AcademicCollaborationStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollaborationStatusHistory> CollaborationStatusHistories { get; set; }
    }
}
