//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicCollaboration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcademicCollaboration()
        {
            this.CollaborationStatusHistories = new HashSet<CollaborationStatusHistory>();
            this.Procedures = new HashSet<Procedure>();
        }
    
        public System.DateTime study_start_date { get; set; }
        public System.DateTime study_end_date { get; set; }
        public int collab_type { get; set; }
        public string note { get; set; }
        public int collab_id { get; set; }
        public int direction { get; set; }
        public int partner_id { get; set; }
        public int people_id { get; set; }
        public int collab_status_id { get; set; }
        public Nullable<bool> is_supported { get; set; }
        public Nullable<int> mou_partner_scope_id { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual AcademicCollaborationStatu AcademicCollaborationStatu { get; set; }
        public virtual MOUPartnerScope MOUPartnerScope { get; set; }
        public virtual Partner Partner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollaborationStatusHistory> CollaborationStatusHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Procedure> Procedures { get; set; }
    }
}
