//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicActivityPhaseLanguage
    {
        public int phase_id { get; set; }
        public int language_id { get; set; }
        public string phase_name { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual AcademicActivityPhase AcademicActivityPhase { get; set; }
    }
}
