//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityPartner
    {
        public int activity_partner_id { get; set; }
        public Nullable<double> sponsor { get; set; }
        public string contact_point_name { get; set; }
        public string contact_point_email { get; set; }
        public string contact_point_phone { get; set; }
        public string evidence { get; set; }
        public Nullable<System.DateTime> cooperation_date_start { get; set; }
        public Nullable<System.DateTime> cooperation_date_end { get; set; }
        public int activity_id { get; set; }
        public Nullable<int> partner_scope_id { get; set; }
    
        public virtual PartnerScope PartnerScope { get; set; }
        public virtual AcademicActivity AcademicActivity { get; set; }
    }
}
