//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalProcess
    {
        public int account_id { get; set; }
        public int request_id { get; set; }
        public int position_id { get; set; }
        public string comment { get; set; }
        public System.DateTime created_date { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Position Position { get; set; }
        public virtual RequestConference RequestConference { get; set; }
    }
}
