//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citation
    {
        public int citation_id { get; set; }
        public int count { get; set; }
        public string link { get; set; }
        public int citation_type_id { get; set; }
        public int request_id { get; set; }
    
        public virtual CitationType CitationType { get; set; }
        public virtual RequestCitation RequestCitation { get; set; }
    }
}
