//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentBase
    {
        public int comment_id { get; set; }
        public int account_id { get; set; }
        public System.DateTime date { get; set; }
        public string content { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual BaseRequest BaseRequest { get; set; }
    }
}
