//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceSupport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConferenceSupport()
        {
            this.ConferenceParticipants = new HashSet<ConferenceParticipant>();
            this.Costs = new HashSet<Cost>();
            this.EligibilityCriterias = new HashSet<EligibilityCriteria>();
            this.Comments = new HashSet<Comment>();
        }
    
        public int conference_support_id { get; set; }
        public int conference_id { get; set; }
        public int reimbursement { get; set; }
        public int status_id { get; set; }
        public Nullable<int> decision_id { get; set; }
        public int reward_policy_id { get; set; }
        public int paper_file_id { get; set; }
        public bool editable { get; set; }
        public int account_id { get; set; }
        public System.DateTime date_request { get; set; }
        public int invitation_file_id { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual File File { get; set; }
        public virtual Conference Conference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceParticipant> ConferenceParticipants { get; set; }
        public virtual ConferenceStatu ConferenceStatu { get; set; }
        public virtual Decision Decision { get; set; }
        public virtual RewardPolicy RewardPolicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cost> Costs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EligibilityCriteria> EligibilityCriterias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
