//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConferenceConditionLanguage
    {
        public int conference_condition_language_id { get; set; }
        public int condition_id { get; set; }
        public int language_id { get; set; }
        public string name { get; set; }
    
        public virtual Condition Condition { get; set; }
        public virtual Language Language { get; set; }
    }
}
