//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost
    {
        public int cost_id { get; set; }
        public int conference_support_id { get; set; }
        public string content { get; set; }
        public string sponsoring_organization { get; set; }
        public string detail { get; set; }
        public int total { get; set; }
        public bool editable { get; set; }
    
        public virtual ConferenceSupport ConferenceSupport { get; set; }
    }
}
