//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class EligibilityCriteria
    {
        public int criteria_id { get; set; }
        public int request_id { get; set; }
        public bool is_accepted { get; set; }
    
        public virtual Criterion Criterion { get; set; }
        public virtual RequestConference RequestConference { get; set; }
    }
}
