//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventionCountry
    {
        public int invention_country_id { get; set; }
        public Nullable<int> invention_id { get; set; }
        public Nullable<int> country_id { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Invention Invention { get; set; }
    }
}
