//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOA()
        {
            this.MOABonus = new HashSet<MOABonu>();
            this.MOAPartnerScopes = new HashSet<MOAPartnerScope>();
            this.MOAStatusHistories = new HashSet<MOAStatusHistory>();
            this.MOAPartners = new HashSet<MOAPartner>();
        }
    
        public int moa_id { get; set; }
        public string moa_code { get; set; }
        public System.DateTime moa_end_date { get; set; }
        public string evidence { get; set; }
        public string moa_note { get; set; }
        public int mou_id { get; set; }
        public int account_id { get; set; }
        public System.DateTime add_time { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual MOU MOU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOABonu> MOABonus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOAPartnerScope> MOAPartnerScopes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOAStatusHistory> MOAStatusHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOAPartner> MOAPartners { get; set; }
    }
}
