//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOAPartnerScope
    {
        public int moa_partner_scope_id { get; set; }
        public int moa_partner_id { get; set; }
        public int mou_partner_scope_id { get; set; }
        public Nullable<int> moa_bonus_id { get; set; }
    
        public virtual MOABonu MOABonu { get; set; }
        public virtual MOAPartner MOAPartner { get; set; }
        public virtual MOUPartnerScope MOUPartnerScope { get; set; }
    }
}
