//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOAPartner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOAPartner()
        {
            this.MOAPartnerScopes = new HashSet<MOAPartnerScope>();
            this.MOAPartnerSpecializations = new HashSet<MOAPartnerSpecialization>();
        }
    
        public int moa_partner_id { get; set; }
        public System.DateTime moa_start_date { get; set; }
        public int moa_id { get; set; }
        public int mou_partner_id { get; set; }
    
        public virtual MOA MOA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOAPartnerScope> MOAPartnerScopes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOAPartnerSpecialization> MOAPartnerSpecializations { get; set; }
        public virtual MOUPartner MOUPartner { get; set; }
    }
}
