//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOAStatusHistory
    {
        public int moa_status_history_id { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string reason { get; set; }
        public Nullable<int> moa_id { get; set; }
        public Nullable<int> mou_status_id { get; set; }
    
        public virtual CollaborationStatu CollaborationStatu { get; set; }
        public virtual MOA MOA { get; set; }
    }
}
