//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOUBonu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOUBonu()
        {
            this.MOUPartnerScopes = new HashSet<MOUPartnerScope>();
        }
    
        public int mou_bonus_id { get; set; }
        public int mou_id { get; set; }
        public string mou_bonus_code { get; set; }
        public System.DateTime mou_bonus_decision_date { get; set; }
        public Nullable<System.DateTime> mou_bonus_end_date { get; set; }
        public Nullable<int> evidence { get; set; }
        public Nullable<int> account_id { get; set; }
        public Nullable<System.DateTime> add_time { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual File File { get; set; }
        public virtual MOU MOU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOUPartnerScope> MOUPartnerScopes { get; set; }
    }
}
