//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOUPartnerScope
    {
        public int partner_scope_id { get; set; }
        public int mou_id { get; set; }
        public Nullable<int> mou_bonus_id { get; set; }
    
        public virtual MOU MOU { get; set; }
        public virtual MOUBonu MOUBonu { get; set; }
        public virtual PartnerScope PartnerScope { get; set; }
    }
}
