//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOUPartner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOUPartner()
        {
            this.MOUPartnerSpecializations = new HashSet<MOUPartnerSpecialization>();
        }
    
        public int mou_partner_id { get; set; }
        public string contact_point_name { get; set; }
        public string contact_point_phone { get; set; }
        public string contact_point_email { get; set; }
        public System.DateTime mou_start_date { get; set; }
        public int mou_id { get; set; }
        public int partner_id { get; set; }
    
        public virtual MOU MOU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOUPartnerSpecialization> MOUPartnerSpecializations { get; set; }
        public virtual Partner Partner { get; set; }
    }
}
