//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOUPartnerSpecialization
    {
        public int mou_partner_specialization_id { get; set; }
        public int mou_partner_id { get; set; }
        public int specialization_id { get; set; }
    
        public virtual Specialization Specialization { get; set; }
        public virtual MOUPartner MOUPartner { get; set; }
    }
}
