//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOUPartnerSpecialization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOUPartnerSpecialization()
        {
            this.MOAPartnerSpecializations = new HashSet<MOAPartnerSpecialization>();
        }
    
        public int mou_partner_specialization_id { get; set; }
        public int mou_partner_id { get; set; }
        public int specialization_id { get; set; }
    
        public virtual Specialization Specialization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOAPartnerSpecialization> MOAPartnerSpecializations { get; set; }
        public virtual MOUPartner MOUPartner { get; set; }
    }
}
