//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOUStatusHistory
    {
        public System.DateTime date { get; set; }
        public string reason { get; set; }
        public int mou_id { get; set; }
        public int mou_status_id { get; set; }
    
        public virtual MOU MOU { get; set; }
        public virtual MOUStatu MOUStatu { get; set; }
    }
}
