//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationSubscribe
    {
        public int account_id { get; set; }
        public int notification_type_id { get; set; }
        public bool is_subscribe { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual NotificationType NotificationType { get; set; }
    }
}
