//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeoplePosition
    {
        public int profile_position_id { get; set; }
        public int people_id { get; set; }
        public int position_id { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Position Position { get; set; }
    }
}
