//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedure
    {
        public int procedure_id { get; set; }
        public int article_id { get; set; }
        public int direction_id { get; set; }
    
        public virtual Direction Direction { get; set; }
        public virtual Article Article { get; set; }
    }
}
