//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfileAcademicDegree
    {
        public Nullable<int> people_id { get; set; }
        public Nullable<int> academic_degree_id { get; set; }
        public int start_year { get; set; }
        public int end_year { get; set; }
        public string study_place { get; set; }
    
        public virtual AcademicDegree AcademicDegree { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
