//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectProduct
    {
        public string link { get; set; }
        public string note { get; set; }
        public int product_id { get; set; }
        public int project_id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ResearchCollaboration ResearchCollaboration { get; set; }
    }
}
