//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestInvention
    {
        public int request_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> total_reward { get; set; }
        public int invention_id { get; set; }
        public string reward_type { get; set; }
    
        public virtual BaseRequest BaseRequest { get; set; }
        public virtual Invention Invention { get; set; }
        public virtual PaperStatu PaperStatu { get; set; }
    }
}
