//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestConference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequestConference()
        {
            this.ApprovalProcesses = new HashSet<ApprovalProcess>();
            this.ConferenceParticipants = new HashSet<ConferenceParticipant>();
            this.Costs = new HashSet<Cost>();
            this.EligibilityCriterias = new HashSet<EligibilityCriteria>();
        }
    
        public int conference_id { get; set; }
        public int reimbursement { get; set; }
        public int status_id { get; set; }
        public int policy_id { get; set; }
        public bool editable { get; set; }
        public int invitation_file_id { get; set; }
        public int paper_id { get; set; }
        public int request_id { get; set; }
        public System.DateTime attendance_start { get; set; }
        public System.DateTime attendance_end { get; set; }
        public int specialization_id { get; set; }
        public Nullable<int> folder_id { get; set; }
    
        public virtual File File { get; set; }
        public virtual File File1 { get; set; }
        public virtual Specialization Specialization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovalProcess> ApprovalProcesses { get; set; }
        public virtual Conference Conference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConferenceParticipant> ConferenceParticipants { get; set; }
        public virtual ConferenceStatu ConferenceStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cost> Costs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EligibilityCriteria> EligibilityCriterias { get; set; }
        public virtual RequestConferencePolicy RequestConferencePolicy { get; set; }
        public virtual Paper Paper { get; set; }
        public virtual BaseRequest BaseRequest { get; set; }
    }
}
