//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestDecision
    {
        public int decision_id { get; set; }
        public int request_id { get; set; }
        public int request_decision_id { get; set; }
    
        public virtual BaseRequest BaseRequest { get; set; }
        public virtual Decision Decision { get; set; }
    }
}
