//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearcherDegree
    {
        public int degree_id { get; set; }
        public int people_id { get; set; }
        public string start_year { get; set; }
        public string end_year { get; set; }
        public string note { get; set; }
        public string study_place { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Degree Degree { get; set; }
    }
}
