//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResearchPartner
    {
        public bool is_sponsor { get; set; }
        public int research_partner_id { get; set; }
        public int project_id { get; set; }
        public Nullable<int> partner_scope_id { get; set; }
    
        public virtual PartnerScope PartnerScope { get; set; }
        public virtual ResearchCollaboration ResearchCollaboration { get; set; }
        public virtual ResearchContactPoint ResearchContactPoint { get; set; }
    }
}
