//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class RightByRole
    {
        public int right_by_role_id { get; set; }
        public int role_id { get; set; }
        public int right_id { get; set; }
    
        public virtual Right Right { get; set; }
        public virtual Role Role { get; set; }
    }
}
