//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scimagojr
    {
        public Nullable<int> Rank { get; set; }
        public double Sourceid { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string Issn { get; set; }
        public Nullable<double> SJR { get; set; }
        public string SJR_Best_Quartile { get; set; }
        public string H_index { get; set; }
        public int Total_Docs_2019 { get; set; }
        public int Total_Docs_3years { get; set; }
        public int Total_Refs { get; set; }
        public int Total_Cites_3years { get; set; }
        public double Citable_Docs_3years { get; set; }
        public double Cites_Doc_2years { get; set; }
        public double Ref_Doc { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
        public string Publisher { get; set; }
        public string Coverage { get; set; }
        public string Categories { get; set; }
    }
}
