//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scopu
    {
        public string Sourcerecord_ID { get; set; }
        public string Source_Title_Medline_sourced_journals_are_indicated_in_Green { get; set; }
        public string Print_ISSN { get; set; }
        public string E_ISSN { get; set; }
        public string Active_or_Inactive { get; set; }
    }
}
