//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENTITIES
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSCI
    {
        public string Journal_title { get; set; }
        public string ISSN { get; set; }
        public string eISSN { get; set; }
        public string Publisher_name { get; set; }
        public string Publisher_address { get; set; }
        public string Languages { get; set; }
        public string Web_of_Science_Categories { get; set; }
        public string SSCI_id { get; set; }
    }
}
