//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUEST.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUEST.Resources.en-US", typeof(en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Activity.
        /// </summary>
        public static string AcademicActivity {
            get {
                return ResourceManager.GetString("AcademicActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study History.
        /// </summary>
        public static string AcadHistory {
            get {
                return ResourceManager.GetString("AcadHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number.
        /// </summary>
        public static string AccNo {
            get {
                return ResourceManager.GetString("AccNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to According to the decision.
        /// </summary>
        public static string According {
            get {
                return ResourceManager.GetString("According", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities During The Year.
        /// </summary>
        public static string ActivityNavbar {
            get {
                return ResourceManager.GetString("ActivityNavbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Study History.
        /// </summary>
        public static string AddAcadHistory {
            get {
                return ResourceManager.GetString("AddAcadHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Article reward request.
        /// </summary>
        public static string AddArticleRequest {
            get {
                return ResourceManager.GetString("AddArticleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more author.
        /// </summary>
        public static string AddAu {
            get {
                return ResourceManager.GetString("AddAu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add award.
        /// </summary>
        public static string AddAward {
            get {
                return ResourceManager.GetString("AddAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Citation reward request.
        /// </summary>
        public static string AddCitationRequest {
            get {
                return ResourceManager.GetString("AddCitationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add conference support request.
        /// </summary>
        public static string AddConfer {
            get {
                return ResourceManager.GetString("AddConfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Conference participation funding request.
        /// </summary>
        public static string AddConferenceRequest {
            get {
                return ResourceManager.GetString("AddConferenceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Invention reward request.
        /// </summary>
        public static string AddInventionRequest {
            get {
                return ResourceManager.GetString("AddInventionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more row.
        /// </summary>
        public static string AddRow {
            get {
                return ResourceManager.GetString("AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add work history.
        /// </summary>
        public static string AddWorkHistory {
            get {
                return ResourceManager.GetString("AddWorkHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string Apr {
            get {
                return ResourceManager.GetString("Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Policies.
        /// </summary>
        public static string ArticlePolicies {
            get {
                return ResourceManager.GetString("ArticlePolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles Reward Requests.
        /// </summary>
        public static string ArticleReward {
            get {
                return ResourceManager.GetString("ArticleReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance list.
        /// </summary>
        public static string AttenList {
            get {
                return ResourceManager.GetString("AttenList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance time.
        /// </summary>
        public static string AttenTime {
            get {
                return ResourceManager.GetString("AttenTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string Aug {
            get {
                return ResourceManager.GetString("Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author&apos;s information.
        /// </summary>
        public static string AuthorInfo {
            get {
                return ResourceManager.GetString("AuthorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author&apos;s name.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Account Information.
        /// </summary>
        public static string BankAccountInformation {
            get {
                return ResourceManager.GetString("BankAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Branch.
        /// </summary>
        public static string BankBranch {
            get {
                return ResourceManager.GetString("BankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a representative to receive the reward.
        /// </summary>
        public static string ChooseRepresentative {
            get {
                return ResourceManager.GetString("ChooseRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ciatation count.
        /// </summary>
        public static string CitationCount {
            get {
                return ResourceManager.GetString("CitationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citation information.
        /// </summary>
        public static string CitationInfo {
            get {
                return ResourceManager.GetString("CitationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citations Reward Requests.
        /// </summary>
        public static string CitationRewardRequests {
            get {
                return ResourceManager.GetString("CitationRewardRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People ID.
        /// </summary>
        public static string CMND {
            get {
                return ResourceManager.GetString("CMND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation.
        /// </summary>
        public static string CmtInfo {
            get {
                return ResourceManager.GetString("CmtInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co-organized unit.
        /// </summary>
        public static string Co_organ {
            get {
                return ResourceManager.GetString("Co-organ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competition.
        /// </summary>
        public static string Competition {
            get {
                return ResourceManager.GetString("Competition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conference.
        /// </summary>
        public static string Confer {
            get {
                return ResourceManager.GetString("Confer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference&apos;s Information.
        /// </summary>
        public static string ConferenceInfor {
            get {
                return ResourceManager.GetString("ConferenceInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference&apos;s name.
        /// </summary>
        public static string ConferenceName {
            get {
                return ResourceManager.GetString("ConferenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference papers.
        /// </summary>
        public static string ConferencePaper {
            get {
                return ResourceManager.GetString("ConferencePaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference Sponsor Requests.
        /// </summary>
        public static string ConferenceSponsorRequests {
            get {
                return ResourceManager.GetString("ConferenceSponsorRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference&apos;s name.
        /// </summary>
        public static string ConferName {
            get {
                return ResourceManager.GetString("ConferName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract type.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria.
        /// </summary>
        public static string Criteria {
            get {
                return ResourceManager.GetString("Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criteria type.
        /// </summary>
        public static string CriteriaType {
            get {
                return ResourceManager.GetString("CriteriaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current policy.
        /// </summary>
        public static string CurrentPolicy {
            get {
                return ResourceManager.GetString("CurrentPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm/dd/yyyy.
        /// </summary>
        public static string DatepickerFormat {
            get {
                return ResourceManager.GetString("DatepickerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/DD/yyyy.
        /// </summary>
        public static string DateRangePickerFormat {
            get {
                return ResourceManager.GetString("DateRangePickerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string Dec {
            get {
                return ResourceManager.GetString("Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove an author.
        /// </summary>
        public static string DelAu {
            get {
                return ResourceManager.GetString("DelAu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a row.
        /// </summary>
        public static string DelRow {
            get {
                return ResourceManager.GetString("DelRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        public static string Dob {
            get {
                return ResourceManager.GetString("Dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domestic.
        /// </summary>
        public static string Domestic {
            get {
                return ResourceManager.GetString("Domestic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Award.
        /// </summary>
        public static string EditAward {
            get {
                return ResourceManager.GetString("EditAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Work History.
        /// </summary>
        public static string EditWorkHistory {
            get {
                return ResourceManager.GetString("EditWorkHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please return to the home page.
        /// </summary>
        public static string EmptyContentDetail {
            get {
                return ResourceManager.GetString("EmptyContentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This article is not available in your language version.
        /// </summary>
        public static string EmptyContentName {
            get {
                return ResourceManager.GetString("EmptyContentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Record.
        /// </summary>
        public static string EmptyTB {
            get {
                return ResourceManager.GetString("EmptyTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper must have at least 1 author.
        /// </summary>
        public static string ErrorAuthorDel {
            get {
                return ResourceManager.GetString("ErrorAuthorDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invention must have at least 1 author.
        /// </summary>
        public static string ErrorAuthorDel2 {
            get {
                return ResourceManager.GetString("ErrorAuthorDel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have at least 1 row.
        /// </summary>
        public static string ErrorCita {
            get {
                return ResourceManager.GetString("ErrorCita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected cost.
        /// </summary>
        public static string ExCost {
            get {
                return ResourceManager.GetString("ExCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string Feb {
            get {
                return ResourceManager.GetString("Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileCM {
            get {
                return ResourceManager.GetString("FileCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload new file.
        /// </summary>
        public static string FileCMnew {
            get {
                return ResourceManager.GetString("FileCMnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formality.
        /// </summary>
        public static string Formal {
            get {
                return ResourceManager.GetString("Formal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPT Procedure.
        /// </summary>
        public static string FPTProcedure {
            get {
                return ResourceManager.GetString("FPTProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERAL INFORMATION.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPT Education - Office of Science Management and International Affairs.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string homepage {
            get {
                return ResourceManager.GetString("homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/assets/media/svg/flags/226-united-states.svg.
        /// </summary>
        public static string icon {
            get {
                return ResourceManager.GetString("icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interested Area.
        /// </summary>
        public static string InterestedArea {
            get {
                return ResourceManager.GetString("InterestedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International.
        /// </summary>
        public static string International {
            get {
                return ResourceManager.GetString("International", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Affair.
        /// </summary>
        public static string InternationalAffair {
            get {
                return ResourceManager.GetString("InternationalAffair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Partners.
        /// </summary>
        public static string InternationalPartner {
            get {
                return ResourceManager.GetString("InternationalPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invention&apos;s name.
        /// </summary>
        public static string InvenName {
            get {
                return ResourceManager.GetString("InvenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invention patents.
        /// </summary>
        public static string Invention {
            get {
                return ResourceManager.GetString("Invention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invention Reward Requests.
        /// </summary>
        public static string InventionRewardRequests {
            get {
                return ResourceManager.GetString("InventionRewardRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISI/SCOPUS Papers.
        /// </summary>
        public static string ISI_SCOPUS {
            get {
                return ResourceManager.GetString("ISI/SCOPUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is reseacher.
        /// </summary>
        public static string isReseacher {
            get {
                return ResourceManager.GetString("isReseacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal index.
        /// </summary>
        public static string JournalIndex {
            get {
                return ResourceManager.GetString("JournalIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal&apos;s name.
        /// </summary>
        public static string JournalName {
            get {
                return ResourceManager.GetString("JournalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal papers.
        /// </summary>
        public static string JournalPaper {
            get {
                return ResourceManager.GetString("JournalPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string Jul {
            get {
                return ResourceManager.GetString("Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string Jun {
            get {
                return ResourceManager.GetString("Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference invitation letter.
        /// </summary>
        public static string Letter {
            get {
                return ResourceManager.GetString("Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link full text.
        /// </summary>
        public static string LinkFull {
            get {
                return ResourceManager.GetString("LinkFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of magazines in the country.
        /// </summary>
        public static string ListMaga {
            get {
                return ResourceManager.GetString("ListMaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load more.
        /// </summary>
        public static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postgraduate Education.
        /// </summary>
        public static string LongTerm {
            get {
                return ResourceManager.GetString("LongTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPT Program.
        /// </summary>
        public static string LongTermFPTProgram {
            get {
                return ResourceManager.GetString("LongTermFPTProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string LongTermIntroduction {
            get {
                return ResourceManager.GetString("LongTermIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Program.
        /// </summary>
        public static string LongTermPartnerProgram {
            get {
                return ResourceManager.GetString("LongTermPartnerProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string Mar {
            get {
                return ResourceManager.GetString("Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee code.
        /// </summary>
        public static string MSNV {
            get {
                return ResourceManager.GetString("MSNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Publications.
        /// </summary>
        public static string NewPublications {
            get {
                return ResourceManager.GetString("NewPublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications settings.
        /// </summary>
        public static string NotificationSettings {
            get {
                return ResourceManager.GetString("NotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string Nov {
            get {
                return ResourceManager.GetString("Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string Oct {
            get {
                return ResourceManager.GetString("Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational units.
        /// </summary>
        public static string OrganUnit {
            get {
                return ResourceManager.GetString("OrganUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper file.
        /// </summary>
        public static string PaperFile {
            get {
                return ResourceManager.GetString("PaperFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper&apos;s information.
        /// </summary>
        public static string PaperInfo {
            get {
                return ResourceManager.GetString("PaperInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper&apos;s name.
        /// </summary>
        public static string PaperName {
            get {
                return ResourceManager.GetString("PaperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper type.
        /// </summary>
        public static string PaperType {
            get {
                return ResourceManager.GetString("PaperType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Detail.
        /// </summary>
        public static string PartnerDetail {
            get {
                return ResourceManager.GetString("PartnerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner List.
        /// </summary>
        public static string PartnerList {
            get {
                return ResourceManager.GetString("PartnerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Name.
        /// </summary>
        public static string PartnerName {
            get {
                return ResourceManager.GetString("PartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Procedure.
        /// </summary>
        public static string PartnerProcedure {
            get {
                return ResourceManager.GetString("PartnerProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patent license date.
        /// </summary>
        public static string PatentDate {
            get {
                return ResourceManager.GetString("PatentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patent number.
        /// </summary>
        public static string PatentNumber {
            get {
                return ResourceManager.GetString("PatentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patent type.
        /// </summary>
        public static string PatentType {
            get {
                return ResourceManager.GetString("PatentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Pre {
            get {
                return ResourceManager.GetString("Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedure Guidelines.
        /// </summary>
        public static string ProcedureGuidelines {
            get {
                return ResourceManager.GetString("ProcedureGuidelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string ProcedureTitle {
            get {
                return ResourceManager.GetString("ProcedureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Picture.
        /// </summary>
        public static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Detail.
        /// </summary>
        public static string ProgramDetail {
            get {
                return ResourceManager.GetString("ProgramDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string ProgramStart {
            get {
                return ResourceManager.GetString("ProgramStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication type.
        /// </summary>
        public static string PublicationType {
            get {
                return ResourceManager.GetString("PublicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish date.
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish&apos;s information.
        /// </summary>
        public static string PublishInfo {
            get {
                return ResourceManager.GetString("PublishInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish&apos;s name.
        /// </summary>
        public static string PublishName {
            get {
                return ResourceManager.GetString("PublishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Time.
        /// </summary>
        public static string PublishTime {
            get {
                return ResourceManager.GetString("PublishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Deadline.
        /// </summary>
        public static string RegistrationDeadline {
            get {
                return ResourceManager.GetString("RegistrationDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related Procedure.
        /// </summary>
        public static string RelatedProcedure {
            get {
                return ResourceManager.GetString("RelatedProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative receives a bonus.
        /// </summary>
        public static string Repre {
            get {
                return ResourceManager.GetString("Repre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request date.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Infomation.
        /// </summary>
        public static string RequestInfo {
            get {
                return ResourceManager.GetString("RequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request List.
        /// </summary>
        public static string RequestList {
            get {
                return ResourceManager.GetString("RequestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Researchers.
        /// </summary>
        public static string Researchers {
            get {
                return ResourceManager.GetString("Researchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Research Major.
        /// </summary>
        public static string ResearchMajor {
            get {
                return ResourceManager.GetString("ResearchMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward.
        /// </summary>
        public static string Reward {
            get {
                return ResourceManager.GetString("Reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward&apos;s information.
        /// </summary>
        public static string RewardInfo {
            get {
                return ResourceManager.GetString("RewardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward type.
        /// </summary>
        public static string RewardType {
            get {
                return ResourceManager.GetString("RewardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Science Technology.
        /// </summary>
        public static string ScienceManagementNavbar {
            get {
                return ResourceManager.GetString("ScienceManagementNavbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Products.
        /// </summary>
        public static string ScientificProducts {
            get {
                return ResourceManager.GetString("ScientificProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publications.
        /// </summary>
        public static string ScientificPublish {
            get {
                return ResourceManager.GetString("ScientificPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendM {
            get {
                return ResourceManager.GetString("SendM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string Sep {
            get {
                return ResourceManager.GetString("Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty Exchange Program.
        /// </summary>
        public static string ShortTerm {
            get {
                return ResourceManager.GetString("ShortTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPT Faculty Exchange Program.
        /// </summary>
        public static string ShortTermFPTProgram {
            get {
                return ResourceManager.GetString("ShortTermFPTProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Faculty Exchange Program.
        /// </summary>
        public static string ShortTermPartnerProgram {
            get {
                return ResourceManager.GetString("ShortTermPartnerProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _START_ to _END_ of _TOTAL_ record.
        /// </summary>
        public static string ShowTB {
            get {
                return ResourceManager.GetString("ShowTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoa Lac High Tech Park, Hanoi, Vietnam.
        /// </summary>
        public static string SMIAAddress {
            get {
                return ResourceManager.GetString("SMIAAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker / organizer members.
        /// </summary>
        public static string Speaker {
            get {
                return ResourceManager.GetString("Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        public static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialized.
        /// </summary>
        public static string Specialized {
            get {
                return ResourceManager.GetString("Specialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsors.
        /// </summary>
        public static string Sponsor {
            get {
                return ResourceManager.GetString("Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string STT {
            get {
                return ResourceManager.GetString("STT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Place.
        /// </summary>
        public static string StudyPlace {
            get {
                return ResourceManager.GetString("StudyPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax code.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code.
        /// </summary>
        public static string TaxCode {
            get {
                return ResourceManager.GetString("TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All team members confirmed the reward type..
        /// </summary>
        public static string TermCondition {
            get {
                return ResourceManager.GetString("TermCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time for the conference.
        /// </summary>
        public static string TimePlace {
            get {
                return ResourceManager.GetString("TimePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total reward.
        /// </summary>
        public static string TotalReward {
            get {
                return ResourceManager.GetString("TotalReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string University {
            get {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information.
        /// </summary>
        public static string UpdateInformation {
            get {
                return ResourceManager.GetString("UpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update information for researcher.
        /// </summary>
        public static string UpdateResearcherInformation {
            get {
                return ResourceManager.GetString("UpdateResearcherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conference venue.
        /// </summary>
        public static string Venue {
            get {
                return ResourceManager.GetString("Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vol.
        /// </summary>
        public static string Vol {
            get {
                return ResourceManager.GetString("Vol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work History.
        /// </summary>
        public static string WorkHistory {
            get {
                return ResourceManager.GetString("WorkHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work unit.
        /// </summary>
        public static string WorkUnit {
            get {
                return ResourceManager.GetString("WorkUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
