//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUEST.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class vi_VN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal vi_VN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUEST.Resources.vi-VN", typeof(vi_VN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạt động học thuật.
        /// </summary>
        public static string AcademicActivity {
            get {
                return ResourceManager.GetString("AcademicActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiểu sử học tập.
        /// </summary>
        public static string AcadHistory {
            get {
                return ResourceManager.GetString("AcadHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        public static string AccNo {
            get {
                return ResourceManager.GetString("AccNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theo quy định.
        /// </summary>
        public static string According {
            get {
                return ResourceManager.GetString("According", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản.
        /// </summary>
        public static string AccountNumber {
            get {
                return ResourceManager.GetString("AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lịch hoạt động trong năm.
        /// </summary>
        public static string ActivityNavbar {
            get {
                return ResourceManager.GetString("ActivityNavbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm tiểu sử học tập.
        /// </summary>
        public static string AddAcadHistory {
            get {
                return ResourceManager.GetString("AddAcadHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề nghị khen thưởng bài báo.
        /// </summary>
        public static string AddArticleRequest {
            get {
                return ResourceManager.GetString("AddArticleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm tác giả.
        /// </summary>
        public static string AddAu {
            get {
                return ResourceManager.GetString("AddAu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm giải thưởng.
        /// </summary>
        public static string AddAward {
            get {
                return ResourceManager.GetString("AddAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề nghị khen thưởng trích dẫn.
        /// </summary>
        public static string AddCitationRequest {
            get {
                return ResourceManager.GetString("AddCitationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm đề nghị hỗ trợ hội nghị.
        /// </summary>
        public static string AddConfer {
            get {
                return ResourceManager.GetString("AddConfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề nghị hỗ trợ hội nghị.
        /// </summary>
        public static string AddConferenceRequest {
            get {
                return ResourceManager.GetString("AddConferenceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đề nghị khen thưởng bằng sáng chế.
        /// </summary>
        public static string AddInventionRequest {
            get {
                return ResourceManager.GetString("AddInventionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm dòng.
        /// </summary>
        public static string AddRow {
            get {
                return ResourceManager.GetString("AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm tiểu sử công tác.
        /// </summary>
        public static string AddWorkHistory {
            get {
                return ResourceManager.GetString("AddWorkHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tất cả.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 4.
        /// </summary>
        public static string Apr {
            get {
                return ResourceManager.GetString("Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu vực.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin chính sách.
        /// </summary>
        public static string ArticlePolicies {
            get {
                return ResourceManager.GetString("ArticlePolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách đề nghị khen thưởng bài báo.
        /// </summary>
        public static string ArticleReward {
            get {
                return ResourceManager.GetString("ArticleReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tham dự.
        /// </summary>
        public static string AttenList {
            get {
                return ResourceManager.GetString("AttenList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian tham dự.
        /// </summary>
        public static string AttenTime {
            get {
                return ResourceManager.GetString("AttenTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 8.
        /// </summary>
        public static string Aug {
            get {
                return ResourceManager.GetString("Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tác giả.
        /// </summary>
        public static string AuthorInfo {
            get {
                return ResourceManager.GetString("AuthorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tác giả.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngân hàng - Chi nhánh ngân hàng.
        /// </summary>
        public static string Bank {
            get {
                return ResourceManager.GetString("Bank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin tài khoản ngân hàng.
        /// </summary>
        public static string BankAccountInformation {
            get {
                return ResourceManager.GetString("BankAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi nhánh.
        /// </summary>
        public static string BankBranch {
            get {
                return ResourceManager.GetString("BankBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiểu sử.
        /// </summary>
        public static string Biography {
            get {
                return ResourceManager.GetString("Biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huỷ.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chọn đại diện nhận thưởng.
        /// </summary>
        public static string ChooseRepresentative {
            get {
                return ResourceManager.GetString("ChooseRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số trích dẫn.
        /// </summary>
        public static string CitationCount {
            get {
                return ResourceManager.GetString("CitationCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin trích dẫn.
        /// </summary>
        public static string CitationInfo {
            get {
                return ResourceManager.GetString("CitationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách đề nghị khen thưởng trích dẫn.
        /// </summary>
        public static string CitationRewardRequests {
            get {
                return ResourceManager.GetString("CitationRewardRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đóng.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMND.
        /// </summary>
        public static string CMND {
            get {
                return ResourceManager.GetString("CMND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin hội thoại.
        /// </summary>
        public static string CmtInfo {
            get {
                return ResourceManager.GetString("CmtInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị đồng tổ chức.
        /// </summary>
        public static string Co_organ {
            get {
                return ResourceManager.GetString("Co-organ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuộc thi/Giải thưởng.
        /// </summary>
        public static string Competition {
            get {
                return ResourceManager.GetString("Competition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hội nghị.
        /// </summary>
        public static string Confer {
            get {
                return ResourceManager.GetString("Confer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin hội nghị.
        /// </summary>
        public static string ConferenceInfor {
            get {
                return ResourceManager.GetString("ConferenceInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hội thảo.
        /// </summary>
        public static string ConferenceName {
            get {
                return ResourceManager.GetString("ConferenceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kỷ yếu hội thảo.
        /// </summary>
        public static string ConferencePaper {
            get {
                return ResourceManager.GetString("ConferencePaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách đề nghị Hỗ trợ hội nghị.
        /// </summary>
        public static string ConferenceSponsorRequests {
            get {
                return ResourceManager.GetString("ConferenceSponsorRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên hội nghị.
        /// </summary>
        public static string ConferName {
            get {
                return ResourceManager.GetString("ConferName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin liên hệ.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nội dung.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại hợp đồng.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi phí.
        /// </summary>
        public static string Cost {
            get {
                return ResourceManager.GetString("Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc gia.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu chí.
        /// </summary>
        public static string Criteria {
            get {
                return ResourceManager.GetString("Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại tiêu chí.
        /// </summary>
        public static string CriteriaType {
            get {
                return ResourceManager.GetString("CriteriaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách hiện tại.
        /// </summary>
        public static string CurrentPolicy {
            get {
                return ResourceManager.GetString("CurrentPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/mm/yyyy.
        /// </summary>
        public static string DatepickerFormat {
            get {
                return ResourceManager.GetString("DatepickerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DD/MM/yyyy.
        /// </summary>
        public static string DateRangePickerFormat {
            get {
                return ResourceManager.GetString("DateRangePickerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 12.
        /// </summary>
        public static string Dec {
            get {
                return ResourceManager.GetString("Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học vị.
        /// </summary>
        public static string Degree {
            get {
                return ResourceManager.GetString("Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa tác giả.
        /// </summary>
        public static string DelAu {
            get {
                return ResourceManager.GetString("DelAu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa dòng.
        /// </summary>
        public static string DelRow {
            get {
                return ResourceManager.GetString("DelRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sinh.
        /// </summary>
        public static string Dob {
            get {
                return ResourceManager.GetString("Dob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trong nước.
        /// </summary>
        public static string Domestic {
            get {
                return ResourceManager.GetString("Domestic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉnh sửa.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thông tin giải thưởng.
        /// </summary>
        public static string EditAward {
            get {
                return ResourceManager.GetString("EditAward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa tiểu sử công tác.
        /// </summary>
        public static string EditWorkHistory {
            get {
                return ResourceManager.GetString("EditWorkHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xin hãy quay về trang chủ.
        /// </summary>
        public static string EmptyContentDetail {
            get {
                return ResourceManager.GetString("EmptyContentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài viết chưa có phiên bản ngôn ngữ của bạn.
        /// </summary>
        public static string EmptyContentName {
            get {
                return ResourceManager.GetString("EmptyContentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không có dữ liệu.
        /// </summary>
        public static string EmptyTB {
            get {
                return ResourceManager.GetString("EmptyTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài báo phải có ít nhất 1 tác giả.
        /// </summary>
        public static string ErrorAuthorDel {
            get {
                return ResourceManager.GetString("ErrorAuthorDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bằng sáng chế phải có ít nhất 1 tác giả.
        /// </summary>
        public static string ErrorAuthorDel2 {
            get {
                return ResourceManager.GetString("ErrorAuthorDel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phải có ít nhất 1 dòng.
        /// </summary>
        public static string ErrorCita {
            get {
                return ResourceManager.GetString("ErrorCita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi phí dự kiến.
        /// </summary>
        public static string ExCost {
            get {
                return ResourceManager.GetString("ExCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 2.
        /// </summary>
        public static string Feb {
            get {
                return ResourceManager.GetString("Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File chứng minh.
        /// </summary>
        public static string FileCM {
            get {
                return ResourceManager.GetString("FileCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file mới.
        /// </summary>
        public static string FileCMnew {
            get {
                return ResourceManager.GetString("FileCMnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hình thức.
        /// </summary>
        public static string Formal {
            get {
                return ResourceManager.GetString("Formal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thủ tục với FPT.
        /// </summary>
        public static string FPTProcedure {
            get {
                return ResourceManager.GetString("FPTProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THÔNG TIN CHUNG.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổ chức giáo dục FPT - Khoa học &amp; Hợp tác quốc tế.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang chủ.
        /// </summary>
        public static string homepage {
            get {
                return ResourceManager.GetString("homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Content/assets/media/svg/flags/220-vietnam.svg.
        /// </summary>
        public static string icon {
            get {
                return ResourceManager.GetString("icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trong.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực quan tâm.
        /// </summary>
        public static string InterestedArea {
            get {
                return ResourceManager.GetString("InterestedArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc tế.
        /// </summary>
        public static string International {
            get {
                return ResourceManager.GetString("International", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hợp tác quốc tế.
        /// </summary>
        public static string InternationalAffair {
            get {
                return ResourceManager.GetString("InternationalAffair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tác quốc tế.
        /// </summary>
        public static string InternationalPartner {
            get {
                return ResourceManager.GetString("InternationalPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên sản phẩm.
        /// </summary>
        public static string InvenName {
            get {
                return ResourceManager.GetString("InvenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bằng sáng chế/GPHI.
        /// </summary>
        public static string Invention {
            get {
                return ResourceManager.GetString("Invention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách đề nhị khen thưởng bằng sáng chế.
        /// </summary>
        public static string InventionRewardRequests {
            get {
                return ResourceManager.GetString("InventionRewardRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bài báo ISI/SCOPUS.
        /// </summary>
        public static string ISI_SCOPUS {
            get {
                return ResourceManager.GetString("ISI/SCOPUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghiên cứu viên.
        /// </summary>
        public static string isReseacher {
            get {
                return ResourceManager.GetString("isReseacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 1.
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ số tạp chí.
        /// </summary>
        public static string JournalIndex {
            get {
                return ResourceManager.GetString("JournalIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tạp chí.
        /// </summary>
        public static string JournalName {
            get {
                return ResourceManager.GetString("JournalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tạp chí khoa học.
        /// </summary>
        public static string JournalPaper {
            get {
                return ResourceManager.GetString("JournalPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 7.
        /// </summary>
        public static string Jul {
            get {
                return ResourceManager.GetString("Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 6.
        /// </summary>
        public static string Jun {
            get {
                return ResourceManager.GetString("Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thư tham dự.
        /// </summary>
        public static string Letter {
            get {
                return ResourceManager.GetString("Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link xác minh.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link toàn văn.
        /// </summary>
        public static string LinkFull {
            get {
                return ResourceManager.GetString("LinkFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tạp chí trong nước.
        /// </summary>
        public static string ListMaga {
            get {
                return ResourceManager.GetString("ListMaga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem thêm.
        /// </summary>
        public static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đào tạo sau đại học.
        /// </summary>
        public static string LongTerm {
            get {
                return ResourceManager.GetString("LongTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đào tạo &lt;br/&gt; của ĐH FPT.
        /// </summary>
        public static string LongTermFPTProgram {
            get {
                return ResourceManager.GetString("LongTermFPTProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giới thiệu &lt;br/&gt; chương trình.
        /// </summary>
        public static string LongTermIntroduction {
            get {
                return ResourceManager.GetString("LongTermIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đào tạo &lt;br/&gt; của đối tác.
        /// </summary>
        public static string LongTermPartnerProgram {
            get {
                return ResourceManager.GetString("LongTermPartnerProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 3.
        /// </summary>
        public static string Mar {
            get {
                return ResourceManager.GetString("Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 5.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSNV/MSSV.
        /// </summary>
        public static string MSNV {
            get {
                return ResourceManager.GetString("MSNV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang cá nhân.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tác giả.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quốc tịch.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công bố mới.
        /// </summary>
        public static string NewPublications {
            get {
                return ResourceManager.GetString("NewPublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tin tức.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang sau.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cài đặt thông báo.
        /// </summary>
        public static string NotificationSettings {
            get {
                return ResourceManager.GetString("NotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 11.
        /// </summary>
        public static string Nov {
            get {
                return ResourceManager.GetString("Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 10.
        /// </summary>
        public static string Oct {
            get {
                return ResourceManager.GetString("Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị.
        /// </summary>
        public static string Office {
            get {
                return ResourceManager.GetString("Office", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tổ chức.
        /// </summary>
        public static string OrganUnit {
            get {
                return ResourceManager.GetString("OrganUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File bài báo.
        /// </summary>
        public static string PaperFile {
            get {
                return ResourceManager.GetString("PaperFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin bài báo.
        /// </summary>
        public static string PaperInfo {
            get {
                return ResourceManager.GetString("PaperInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên bài báo.
        /// </summary>
        public static string PaperName {
            get {
                return ResourceManager.GetString("PaperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại ấn phẩm.
        /// </summary>
        public static string PaperType {
            get {
                return ResourceManager.GetString("PaperType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đối tác.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết đối tác.
        /// </summary>
        public static string PartnerDetail {
            get {
                return ResourceManager.GetString("PartnerDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách đối tác.
        /// </summary>
        public static string PartnerList {
            get {
                return ResourceManager.GetString("PartnerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đối tác.
        /// </summary>
        public static string PartnerName {
            get {
                return ResourceManager.GetString("PartnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thủ tục với đối tác.
        /// </summary>
        public static string PartnerProcedure {
            get {
                return ResourceManager.GetString("PartnerProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày cấp.
        /// </summary>
        public static string PatentDate {
            get {
                return ResourceManager.GetString("PatentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số bằng sáng chế.
        /// </summary>
        public static string PatentNumber {
            get {
                return ResourceManager.GetString("PatentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại SHTT.
        /// </summary>
        public static string PatentType {
            get {
                return ResourceManager.GetString("PatentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SĐT.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chính sách.
        /// </summary>
        public static string Policy {
            get {
                return ResourceManager.GetString("Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang trước.
        /// </summary>
        public static string Pre {
            get {
                return ResourceManager.GetString("Pre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin học bổng.
        /// </summary>
        public static string ProcedureGuidelines {
            get {
                return ResourceManager.GetString("ProcedureGuidelines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu đề.
        /// </summary>
        public static string ProcedureTitle {
            get {
                return ResourceManager.GetString("ProcedureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên.
        /// </summary>
        public static string ProfileName {
            get {
                return ResourceManager.GetString("ProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ảnh hồ sơ.
        /// </summary>
        public static string ProfilePicture {
            get {
                return ResourceManager.GetString("ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chương trình.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chi tiết chương trình.
        /// </summary>
        public static string ProgramDetail {
            get {
                return ResourceManager.GetString("ProgramDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian bắt đầu.
        /// </summary>
        public static string ProgramStart {
            get {
                return ResourceManager.GetString("ProgramStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại ấn phẩm.
        /// </summary>
        public static string PublicationType {
            get {
                return ResourceManager.GetString("PublicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày xuất bản.
        /// </summary>
        public static string PublishDate {
            get {
                return ResourceManager.GetString("PublishDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin nhà xuất bản.
        /// </summary>
        public static string PublishInfo {
            get {
                return ResourceManager.GetString("PublishInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà xuất bản.
        /// </summary>
        public static string PublishName {
            get {
                return ResourceManager.GetString("PublishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày đăng.
        /// </summary>
        public static string PublishTime {
            get {
                return ResourceManager.GetString("PublishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chất lượng.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thứ hạng.
        /// </summary>
        public static string Ranking {
            get {
                return ResourceManager.GetString("Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bản ghi.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng ký tham dự.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời hạn đăng ký.
        /// </summary>
        public static string RegistrationDeadline {
            get {
                return ResourceManager.GetString("RegistrationDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Các thủ tục liên quan.
        /// </summary>
        public static string RelatedProcedure {
            get {
                return ResourceManager.GetString("RelatedProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại diện nhận thưởng.
        /// </summary>
        public static string Repre {
            get {
                return ResourceManager.GetString("Repre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày gửi yêu cầu.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin yêu cầu.
        /// </summary>
        public static string RequestInfo {
            get {
                return ResourceManager.GetString("RequestInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách yêu cầu.
        /// </summary>
        public static string RequestList {
            get {
                return ResourceManager.GetString("RequestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nghiên cứu viên.
        /// </summary>
        public static string Researchers {
            get {
                return ResourceManager.GetString("Researchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực nghiên cứu.
        /// </summary>
        public static string ResearchMajor {
            get {
                return ResourceManager.GetString("ResearchMajor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền thưởng.
        /// </summary>
        public static string Reward {
            get {
                return ResourceManager.GetString("Reward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin xét thưởng.
        /// </summary>
        public static string RewardInfo {
            get {
                return ResourceManager.GetString("RewardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại khen thưởng.
        /// </summary>
        public static string RewardType {
            get {
                return ResourceManager.GetString("RewardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lưu.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoa học – Công nghệ.
        /// </summary>
        public static string ScienceManagementNavbar {
            get {
                return ResourceManager.GetString("ScienceManagementNavbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sản phẩm khoa học.
        /// </summary>
        public static string ScientificProducts {
            get {
                return ResourceManager.GetString("ScientificProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công trình khoa học.
        /// </summary>
        public static string ScientificPublish {
            get {
                return ResourceManager.GetString("ScientificPublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi đề nghị.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người gửi.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gửi.
        /// </summary>
        public static string SendM {
            get {
                return ResourceManager.GetString("SendM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tháng 9.
        /// </summary>
        public static string Sep {
            get {
                return ResourceManager.GetString("Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trao đổi giảng viên ngắn hạn.
        /// </summary>
        public static string ShortTerm {
            get {
                return ResourceManager.GetString("ShortTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trao đổi với FPT.
        /// </summary>
        public static string ShortTermFPTProgram {
            get {
                return ResourceManager.GetString("ShortTermFPTProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trao đổi với đối tác.
        /// </summary>
        public static string ShortTermPartnerProgram {
            get {
                return ResourceManager.GetString("ShortTermPartnerProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiển thị.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang hiển thị từ _START_ đến _END_ của _TOTAL_ bản ghi.
        /// </summary>
        public static string ShowTB {
            get {
                return ResourceManager.GetString("ShowTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khu CNC Hoà Lạc, Hà Nội, Việt Nam.
        /// </summary>
        public static string SMIAAddress {
            get {
                return ResourceManager.GetString("SMIAAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiêu chí trích dẫn.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diễn giả/ Thành viên BTC.
        /// </summary>
        public static string Speaker {
            get {
                return ResourceManager.GetString("Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lĩnh vực.
        /// </summary>
        public static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chuyên ngành.
        /// </summary>
        public static string Specialized {
            get {
                return ResourceManager.GetString("Specialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tài trợ.
        /// </summary>
        public static string Sponsor {
            get {
                return ResourceManager.GetString("Sponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạng thái.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STT.
        /// </summary>
        public static string STT {
            get {
                return ResourceManager.GetString("STT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nơi học tập.
        /// </summary>
        public static string StudyPlace {
            get {
                return ResourceManager.GetString("StudyPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        public static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        public static string TaxCode {
            get {
                return ResourceManager.GetString("TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lựa chọn loại khen thưởng đã được xác nhận bởi tất cả các thành viên trong nhóm.
        /// </summary>
        public static string TermCondition {
            get {
                return ResourceManager.GetString("TermCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian diễn ra.
        /// </summary>
        public static string TimePlace {
            get {
                return ResourceManager.GetString("TimePlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức danh.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng cộng.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổng thưởng.
        /// </summary>
        public static string TotalReward {
            get {
                return ResourceManager.GetString("TotalReward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thuôc trường đại học.
        /// </summary>
        public static string University {
            get {
                return ResourceManager.GetString("University", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin.
        /// </summary>
        public static string UpdateInformation {
            get {
                return ResourceManager.GetString("UpdateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thông tin cho nghiên cứu viên.
        /// </summary>
        public static string UpdateResearcherInformation {
            get {
                return ResourceManager.GetString("UpdateResearcherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa điểm tổ chức.
        /// </summary>
        public static string Venue {
            get {
                return ResourceManager.GetString("Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xem chi tiết.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tập.
        /// </summary>
        public static string Vol {
            get {
                return ResourceManager.GetString("Vol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang web.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiểu sử công tác.
        /// </summary>
        public static string WorkHistory {
            get {
                return ResourceManager.GetString("WorkHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cơ sở.
        /// </summary>
        public static string WorkUnit {
            get {
                return ResourceManager.GetString("WorkUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Năm.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
